int n_back = -1;
int space_bit = 0;
int j_bit = 0;
int first_o = 0;
int derg_bit = 1;
int	derg_count ;
int spec_kgun = 0;
int spec_kgun_val;
int found = 0;
int f_bit = 0;
int s_bit = 0;
int p_bit = 0;
int ei_bit = 0;
int c_bit = 0;
int ipressed = 0;
int o_bit = 0;
int x_bit = 0;
int so_bit = 0;
//int X_bit  = 0;
